import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  en: {
    // Nav
    home: "Home",
    features: "Features",
    whoItsFor: "Who It's For",
    getStarted: "Get Started",
    dashboard: "Dashboard",
    signIn: "Sign In",
    signUp: "Sign Up",
    email: "Email Address",
    password: "Password",
    fullName: "Full Name",
    alreadyHaveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    loginTitle: "Welcome Back",
    registerTitle: "Create Account",
    welcomeBack: "Welcome back",
    clinicSummary: "Here's your clinic summary for today.",
    totalAppointments: "Total Appointments",
    confirmed: "Confirmed",
    completed: "Completed",
    noShow: "No Show",
    manageSchedule: "Manage Schedule",
    viewAppointments: "View Appointments",
    myAvailability: "My Availability",
    loadingDashboard: "Loading dashboard...",
    doctorSchedule: "Doctor's Schedule",
    viewAppointmentsSubtitle: "View your appointments and add clinical notes.",
    noAppointments: "No Appointments",
    noAppointmentsSubtitle: "You have an empty schedule for this date.",
    allDoctors: "All Doctors",
    patient: "Patient",
    phone: "Phone",
    reference: "Reference",
    paid: "Paid",
    unpaid: "Unpaid",
    markPaid: "Mark Paid",
    clinicalNotes: "Clinical Notes",
    noNotes: "No clinical notes added yet.",
    saveNote: "Save Note",
    cancel: "Cancel",
    addNotePlaceholder: "Type clinical notes here...",
    statusPending: "Pending",
    statusConfirmed: "Confirmed",
    statusCancelled: "Cancelled",
    statusRescheduled: "Rescheduled",
    statusCompleted: "Completed",
    statusNoShow: "No Show",
    myAppointments: "My Appointments",
    myAppointmentsSubtitle: "Your clinic bookings and medical service history.",
    total: "Total",
    syncingRecords: "Syncing your clinical records...",
    noAppointmentsFound: "No Appointments Found",
    noAppointmentsFoundSubtitle: "You haven't scheduled any medical services yet. Browse available slots to get started.",
    returnToDashboard: "Return to Dashboard",
    updateStatus: "Update Status",
    cancelAppointment: "Cancel Appointment",
    confirmCancel: "Are you sure you want to cancel this appointment?",
    cancelling: "Cancelling appointment...",
    cancelledSuccess: "Appointment cancelled",
    cancelledFailed: "Cancellation failed",
    updatingStatus: "Updating status...",
    statusUpdated: "Status updated",
    updateFailed: "Update failed",
    patients: "Patients",
    patientsSubtitle: "Registry of all registered clinic patients.",
    searchPlaceholder: "Search by name or email...",
    patientInfo: "Patient Information",
    contactDetails: "Contact Details",
    status: "Status",
    joined: "Joined",
    active: "Active",
    noPatientsFound: "No matching patient records found.",
    fetchingRegistry: "Fetching registry...",
    doctors: "Doctors",
    doctorsSubtitle: "Manage clinic doctors and their schedules.",
    addDoctor: "Add Doctor",
    editDoctor: "Edit Doctor",
    deleteDoctor: "Delete Doctor",
    viewSchedule: "View Schedule",
    noDoctorsFound: "No Doctors Found",
    noDoctorsFoundSubtitle: "Register new doctors via the Add Doctor button above.",
    addFirstDoctor: "Add First Doctor",
    doctorName: "Doctor Name",
    emailLogin: "Email (Login Username)",
    password: "Password",
    specialty: "Specialty",
    bio: "Bio",
    doctorPhoto: "Doctor Photo",
    photoUploadTip: "* Select a doctor to upload their photo.",
    saveDoctor: "Save Doctor",
    updatingDoctor: "Updating doctor...",
    addingDoctor: "Adding doctor...",
    doctorUpdated: "Doctor updated successfully!",
    doctorAdded: "Doctor added successfully!",
    deleteConfirm: "Are you sure? This will permanently delete the doctor record.",
    deletingDoctor: "Deleting doctor...",
    doctorDeleted: "Doctor deleted",
    deleteFailed: "Failed to delete doctor",
    addWorkingHours: "Add Working Hours",
    durationMin: "Duration (min)",
    scheduleAdded: "Schedule added",
    scheduleFailed: "Failed to add schedule",
    scheduleRemoved: "Schedule removed",
    removeScheduleFailed: "Failed to remove schedule",
    noWorkingHours: "No working hours defined.",
    workingHours: "Working Hours",
    close: "Close",
    daySunday: "Sunday",
    dayMonday: "Monday",
    dayTuesday: "Tuesday",
    dayWednesday: "Wednesday",
    dayThursday: "Thursday",
    dayFriday: "Friday",
    daySaturday: "Saturday",
    bookNow: "Book Now",
    manageBooking: "Manage Booking",
    
    // Hero
    heroTitle: "Smart healthcare management for modern clinics.",
    heroSubtitle: "From automated doctor scheduling to seamless patient bookings — everything you need to run a high-performance clinic in one platform.",
    bookAppointment: "Book an Appointment",
    
    // Doctors
    doctors: "Doctors",
    addDoctor: "Add Doctor",
    editDoctor: "Edit Doctor",
    specialty: "Specialty",
    bio: "Biography",
    noBio: "No biography provided.",
    viewSchedule: "View Schedule",
    
    // Dashboard
    welcome: "Welcome back",
    summary: "Here's your clinic summary for today.",
    totalAppointments: "Total Appointments",
    confirmed: "Confirmed",
    completed: "Completed",
    
    // Common
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    actions: "Actions",

    // Guest Booking
    chooseDoctor: "Choose Your Specialist",
    selectSpecialistSubtitle: "Select a doctor to view their available time slots.",
    selectSpecialist: "Select Doctor",
    selectTime: "Select Time Slot",
    changeDoctor: "Change Doctor",
    chooseDate: "Choose Date",
    checkingAvailability: "Checking availability...",
    noSlotsAvailable: "No slots available for this date.",
    continue: "Continue",
    yourDetails: "Your Contact Details",
    back: "Back",
    appointmentSummary: "Appointment Summary",
    emailAddress: "Email Address",
    notes: "Notes",
    confirmBooking: "Confirm Booking",
    bookingConfirmed: "Booking Confirmed!",
    yourReference: "Your Booking Reference",
    saveReferenceHint: "Save this reference to manage your booking later.",
    manageBookings: "Manage Bookings",
    backToHome: "Back to Home"
  },
  ar: {
    // Nav
    home: "الرئيسية",
    features: "المميزات",
    whoItsFor: "لمن هذا؟",
    getStarted: "ابدأ الآن",
    dashboard: "لوحة التحكم",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    fullName: "الاسم الكامل",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    noAccount: "ليس لديك حساب؟",
    loginTitle: "مرحباً بعودتك",
    registerTitle: "إنشاء حساب جديد",
    welcomeBack: "مرحباً بعودتك",
    clinicSummary: "إليك ملخص العيادة لهذا اليوم.",
    totalAppointments: "إجمالي المواعيد",
    confirmed: "مؤكد",
    completed: "مكتمل",
    noShow: "عدم حضور",
    manageSchedule: "إدارة الجدول",
    viewAppointments: "عرض المواعيد",
    myAvailability: "جاهزيتي",
    loadingDashboard: "جاري تحميل لوحة التحكم...",
    doctorSchedule: "جدول الطبيب",
    viewAppointmentsSubtitle: "استعرض مواعيدك وأضف ملاحظاتك الطبية.",
    noAppointments: "لا توجد مواعيد",
    noAppointmentsSubtitle: "جدولك فارغ لهذا التاريخ.",
    allDoctors: "جميع الأطباء",
    patient: "المريض",
    phone: "الهاتف",
    reference: "المرجع",
    paid: "مدفوع",
    unpaid: "غير مدفوع",
    markPaid: "تحديد كمدفوع",
    clinicalNotes: "الملاحظات الطبية",
    noNotes: "لم يتم إضافة ملاحظات طبية بعد.",
    saveNote: "حفظ الملاحظة",
    cancel: "إلغاء",
    addNotePlaceholder: "اكتب الملاحظات الطبية هنا...",
    statusPending: "قيد الانتظار",
    statusConfirmed: "مؤكد",
    statusCancelled: "ملغي",
    statusRescheduled: "تمت إعادة الجدولة",
    statusCompleted: "مكتمل",
    statusNoShow: "عدم حضور",
    myAppointments: "مواعيدي",
    myAppointmentsSubtitle: "حجوزاتك في العيادة وسجلك الطبي.",
    total: "الإجمالي",
    syncingRecords: "جاري مزامنة سجلاتك الطبية...",
    noAppointmentsFound: "لم يتم العثور على مواعيد",
    noAppointmentsFoundSubtitle: "لم تقم بجدولة أي خدمات طبية بعد. تصفح المواعيد المتاحة للبدء.",
    returnToDashboard: "العودة للوحة التحكم",
    updateStatus: "تحديث الحالة",
    cancelAppointment: "إلغاء الموعد",
    confirmCancel: "هل أنت متأكد أنك تريد إلغاء هذا الموعد؟",
    cancelling: "جاري إلغاء الموعد...",
    cancelledSuccess: "تم إلغاء الموعد",
    cancelledFailed: "فشل الإلغاء",
    updatingStatus: "جاري تحديث الحالة...",
    statusUpdated: "تم تحديث الحالة",
    updateFailed: "فشل التحديث",
    patients: "المرضى",
    patientsSubtitle: "سجل جميع المرضى المسجلين في العيادة.",
    searchPlaceholder: "ابحث بالاسم أو البريد الإلكتروني...",
    patientInfo: "معلومات المريض",
    contactDetails: "تفاصيل الاتصال",
    status: "الحالة",
    joined: "تاريخ الانضمام",
    active: "نشط",
    noPatientsFound: "لم يتم العثور على سجلات مرضى مطابقة.",
    fetchingRegistry: "جاري جلب السجل...",
    doctors: "الأطباء",
    doctorsSubtitle: "إدارة أطباء العيادة وجداول مواعيدهم.",
    addDoctor: "إضافة طبيب",
    editDoctor: "تعديل بيانات الطبيب",
    deleteDoctor: "حذف الطبيب",
    viewSchedule: "عرض الجدول",
    noDoctorsFound: "لم يتم العثور على أطباء",
    noDoctorsFoundSubtitle: "قم بتسجيل أطباء جدد عبر زر إضافة طبيب أعلاه.",
    addFirstDoctor: "إضافة أول طبيب",
    doctorName: "اسم الطبيب",
    emailLogin: "البريد الإلكتروني (اسم المستخدم)",
    password: "كلمة المرور",
    specialty: "التخصص",
    bio: "السيرة الذاتية",
    doctorPhoto: "صورة الطبيب",
    photoUploadTip: "* اختر طبيباً لرفع صورته.",
    saveDoctor: "حفظ البيانات",
    updatingDoctor: "جاري تحديث بيانات الطبيب...",
    addingDoctor: "جاري إضافة الطبيب...",
    doctorUpdated: "تم تحديث بيانات الطبيب بنجاح!",
    doctorAdded: "تم إضافة الطبيب بنجاح!",
    deleteConfirm: "هل أنت متأكد؟ سيؤدي هذا إلى حذف سجل الطبيب نهائياً.",
    deletingDoctor: "جاري حذف الطبيب...",
    doctorDeleted: "تم حذف الطبيب",
    deleteFailed: "فشل حذف الطبيب",
    addWorkingHours: "إضافة ساعات عمل",
    durationMin: "المدة (دقيقة)",
    scheduleAdded: "تم إضافة الجدول",
    scheduleFailed: "فشل إضافة الجدول",
    scheduleRemoved: "تم إزالة الجدول",
    removeScheduleFailed: "فشل إزالة الجدول",
    noWorkingHours: "لا توجد ساعات عمل محددة.",
    workingHours: "ساعات العمل",
    close: "إغلاق",
    daySunday: "الأحد",
    dayMonday: "الإثنين",
    dayTuesday: "الثلاثاء",
    dayWednesday: "الأربعاء",
    dayThursday: "الخميس",
    dayFriday: "الجمعة",
    daySaturday: "السبت",
    bookNow: "احجز الآن",
    manageBooking: "إدارة الحجز",
    
    // Hero
    heroTitle: "إدارة رعاية صحية ذكية للعيادات الحديثة.",
    heroSubtitle: "من الجدولة الآلية للأطباء إلى حجوزات المرضى السلسة — كل ما تحتاجه لإدارة عيادة عالية الأداء في منصة واحدة.",
    bookAppointment: "احجز موعداً",
    
    // Doctors
    doctors: "الأطباء",
    addDoctor: "إضافة طبيب",
    editDoctor: "تعديل بيانات الطبيب",
    specialty: "التخصص",
    bio: "السيرة الذاتية",
    noBio: "لا يوجد وصف حالياً.",
    viewSchedule: "عرض الجدول",
    
    // Dashboard
    welcome: "مرحباً بك مجدداً",
    summary: "إليك ملخص العيادة لهذا اليوم.",
    totalAppointments: "إجمالي المواعيد",
    confirmed: "مؤكد",
    completed: "مكتمل",
    
    // Common
    save: "حفظ",
    cancel: "إلغاء",
    loading: "جارٍ التحميل...",
    actions: "الإجراءات",

    // Guest Booking (Arabic)
    chooseDoctor: "اختر أخصائيك",
    selectSpecialistSubtitle: "اختر طبيباً لاستعراض المواعيد المتاحة لديه.",
    selectSpecialist: "اختر الطبيب",
    selectTime: "اختر وقت الموعد",
    changeDoctor: "تغيير الطبيب",
    chooseDate: "اختر التاريخ",
    checkingAvailability: "جاري التحقق من التوافر...",
    noSlotsAvailable: "لا توجد مواعيد متاحة لهذا التاريخ.",
    continue: "متابعة",
    yourDetails: "تفاصيل الاتصال الخاصة بك",
    back: "رجوع",
    appointmentSummary: "ملخص الموعد",
    emailAddress: "البريد الإلكتروني",
    notes: "ملاحظات",
    confirmBooking: "تأكيد الحجز",
    bookingConfirmed: "تم تأكيد الحجز!",
    yourReference: "رقم المرجع الخاص بك",
    saveReferenceHint: "احفظ هذا المرجع لتتمكن من إدارة حجزك لاحقاً.",
    manageBookings: "إدارة الحجوزات",
    backToHome: "العودة للرئيسية"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem("clinicflow_lang") || "en");
  
  useEffect(() => {
    localStorage.setItem("clinicflow_lang", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  const toggleLang = () => {
    setLang(prev => prev === "en" ? "ar" : "en");
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLang, isRtl: lang === "ar" }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
